### ISSUE TITLE
error 500 after installing the API on Ubuntu server 16.04

### ISSUE THREAD

**Issue by JBroeren** [bytesizedhosting/bcd#41]
after successfully installing the API-key. The website asks me to click on the Check connection button. I do this but after doing this I get to see error 500 in my web browser. I tried to reinstall the connect program a few times, I did a full re-installation of my server. All of it just didn't help at all. I keep getting the error. I also checked whether the docker, BCD or BCD-proxy properly installed on it's own. the BCD and BCD-proxy do BUT. If I do apt-get install docker after installing the API-key. It gives me the message

Reading package lists... Done Building dependency tree Reading state information... Done The following NEW packages will be installed: docker 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded. Need to get 0 B/12.2 kB of archives. After this operation, 65.5 kB of additional disk space will be used. Selecting previously unselected package docker. (Reading database ... 92231 files and directories currently installed.) Preparing to unpack .../docker_1.5-1_amd64.deb ... Unpacking docker (1.5-1) ... Processing triggers for man-db (2.7.5-1) ... Setting up docker (1.5-1) ...

which is weird because you would think docker was installed with the API-key. After finding out about this I reinstalled again but with a docker re installment before the installment of the API-key. Which unfortunately didn't help...

I hope there is actually a solution to this. Prior to all of this I actually managed to get your service running but I uninstalled it back then (2 days ago) because I thought it would interfere with programs that were already installed at that moment. So I did a re-installation, installed bytesized API-key, the service gave me the 500 error. reinstalled API-key a few times using the uninstallation method provided on your site:

apt-get remove docker service bcd stop service bcd-proxy stop rm /usr/local/bin/bcd && rm /usr/local/bin/bcd-proxy && rm /lib/systemd/system/bcd.service && rm /lib/systemd/system/bcd-proxy.service

reinstalled the system after that and now I can't manage to install it again. Please help me because I did have the privilege to use your system litterally a day ago. But now I just can't manage to use it again and that is really a miss.

I could really use some help so please. Help everyone by helping me!

**Comment by JBroeren** [comment]
the code inserted in the text message, resupplied properly
first number of lines:
`apt-get remove docker
 service bcd stop
 service bcd-proxy
 stop rm /usr/local/bin/bcd && rm /usr/local/bin/bcd-proxy && rm /lib/systemd/system/bcd.service && rm /lib/systemd/system/bcd-proxy.service`

second number of lines:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  docker
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 12.8 kB of archives.
After this operation, 42.0 kB of additional disk space will be used.
Get:1 http://ftp2.nluug.nl/os/Linux/distr/kali kali-rolling/main amd64 docker amd64 1.5-1+b1 [12.8 kB]
Fetched 12.8 kB in 0s (14.0 kB/s)
Selecting previously unselected package docker.
(Reading database ... 453692 files and directories currently installed.)
Preparing to unpack .../docker_1.5-1+b1_amd64.deb ...
Unpacking docker (1.5-1+b1) ...
Processing triggers for menu (2.1.47+b1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up docker (1.5-1+b1) ...
Processing triggers for menu (2.1.47+b1) ...`

**Comment by maran** [comment]
Can you please confirm you are using Ubuntu 14.04 or 16.04. These are the only supported by the automatic installation script.

**Comment by JBroeren** [comment]
Yes I am currently using it on ubuntu server 16.04

Op 17 mrt. 2017 17:49 schreef "Maran" <notifications@github.com>:

**Comment by maran** [comment]
Could you tell me your Bytesized username and the output of `cat /etc/lsb-release` and `uname -a` and `cat /proc/cpuinfo`?

**Comment by JBroeren** [comment]
cat /etc/lsb-release:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

uname -a:
Linux ubuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017
x86_64 x86_64 x86_64 GNU/Linux

cat /proc/cpuinfo:
processor    : 0
vendor_id    : AuthenticAMD
cpu family    : 15
model        : 75
model name    : AMD Athlon(tm) 64 X2 Dual Core Processor 4200+
stepping    : 2
cpu MHz        : 2204.624
cache size    : 512 KB
physical id    : 0
siblings    : 2
core id        : 0
cpu cores    : 2
apicid        : 0
initial apicid    : 0
fpu        : yes
fpu_exception    : yes
cpuid level    : 1
wp        : yes
flags        : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt
rdtscp lm 3dnowext 3dnow rep_good nopl extd_apicid pni cx16 lahf_lm
cmp_legacy svm extapic cr8_legacy 3dnowprefetch vmmcall
bugs        : apic_c1e fxsave_leak sysret_ss_attrs
bogomips    : 4409.24
TLB size    : 1024 4K pages
clflush size    : 64
cache_alignment    : 64
address sizes    : 40 bits physical, 48 bits virtual
power management: ts fid vid ttp tm stc

cat proc/cpuinfo
processor    : 1
vendor_id    : AuthenticAMD
cpu family    : 15
model        : 75
model name    : AMD Athlon(tm) 64 X2 Dual Core Processor 4200+
stepping    : 2
cpu MHz        : 2204.624
cache size    : 512 KB
physical id    : 0
siblings    : 2
core id        : 1
cpu cores    : 2
apicid        : 1
initial apicid    : 1
fpu        : yes
fpu_exception    : yes
cpuid level    : 1
wp        : yes
flags        : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca
cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt
rdtscp lm 3dnowext 3dnow rep_good nopl extd_apicid pni cx16 lahf_lm
cmp_legacy svm extapic cr8_legacy 3dnowprefetch vmmcall
bugs        : apic_c1e fxsave_leak sysret_ss_attrs
bogomips    : 4409.14
TLB size    : 1024 4K pages
clflush size    : 64
cache_alignment    : 64
address sizes    : 40 bits physical, 48 bits virtual
power management: ts fid vid ttp tm stc

there you go, I hope this is what you asked for! thanks for helping me.

Aangezien ik zag dat u uit amsterdam kwam dacht ik, misschien kan dit ook
wel gewoon in het Nederlands? zo ja, leuk! Anders is Engels prima.

Jacco Broeren

2017-03-18 7:26 GMT+01:00 Maran <notifications@github.com>:

**Comment by JBroeren** [comment]
Did something went wrong, since I didn't get any response. I assume you're
trying to fix it, if you run in any info missing on your way to finding a
solution. Just ask me to provide the needed info for you!

greetings Jacco Broeren

2017-03-18 13:20 GMT+01:00 Jacco Bunnik <jaccobroeren.apple@gmail.com>:

**Comment by maran** [comment]
You did not give me your Bytesized Username yet. Let me know and I will check it out.

**Comment by JBroeren** [comment]
jaccobroeren

Op 20 mrt. 2017 8:14 a.m. schreef "Maran" <notifications@github.com>:

**Comment by JBroeren** [comment]
I'm sorry, my display name is jb2210.

Op 20 mrt. 2017 9:07 a.m. schreef "Jacco broeren"

**Comment by maran** [comment]
Some device on route from my website to your home server is refusing the connection. 

Either XS4All is blocking the connection on purpose or your router/firewall is blocking it. Both traceroutes as any connection to port 8112 is being actively blocked.

I've updated the website to not give you an generic error anymore but tell you a bit more about the actual problem so others won't bang their heads against this.

**Comment by JBroeren** [comment]
oke thank you, I will look into it. Also nice for other people to see what
actually is the problem.

Also an idea for an extra app to add to the applications list in bytesized
connect is Radarr (https://github.com/Radarr/Radarr). It's a gitfork from
Sonarr and works flawless. I'm not sure if bytesized includes indexing rss
feeds for sonarr. But you can use exactly the same indexers on radarr
configured the same way. Hope this will help you to add more applications
so that you can make bytesized connect even bigger.

ps. if you are still looking for a way of easy adding idexing rss links to
sanarr and as future program radarr, check out jackett.
https://github.com/Jackett/Jackett

If you'd like extra recommendations on new program's, happy to give them!

Jacco Broeren

2017-03-20 9:21 GMT+01:00 Maran <notifications@github.com>:
