### ISSUE TITLE
App Request: NZBHydra

### ISSUE THREAD

**Issue by volvicTM** [bytesizedhosting/bcd#42]
Any chance to get NZBHydra onto BCD? Docker: https://github.com/linuxserver/docker-hydra

**Comment by maran** [comment]
I am open to this, if you can I do accept pull requests :)

**Comment by aSapien** [comment]
Hi @maran , I'm looking for a way to setup Index priorities in Sonarr on my Bytesized server. So far, [the only solution I found](https://www.reddit.com/r/radarr/comments/ao5ot5/anyway_to_prioritize_an_indexer_over_another/efyco7d/) is to use [NZBHydra2](https://github.com/theotherp/nzbhydra2), which I'm not familiar enough with.

1. Is there any other working solution?
2. How much estimated work is it to add NZBHydra2 to BCD? (considering no familiarity with the source code)

**Comment by maran** [comment]
Sorry I have no idea what index priorities are. 

If you know Go it will probably be an hour or two to build in support depending on how hard it is to create a user from the command line. Alternatively just grab a random docker image and run it manually. The great thing about BCD is that it compliments your server and does not take it over so you can still install any app however you want it.

**Comment by aSapien** [comment]
Apologies, I meant "Index**er**" priority

**Comment by maran** [comment]
I have no experience with that and I don't think this is the place to ask. Try using the Sonarr forums.
