### ISSUE TITLE
Cert expired - download.bytesized-hosting.com

### ISSUE THREAD

**Issue by nunsie** [bytesizedhosting/bcd#45]
SSL Cert for download.bytesized-hosting.com expired a few hours ago, making it impossible to install BCD as curl fails on validating the cert.

**Comment by nunsie** [comment]
Made a gist for a temporary workaround - ignores the expired certs: https://gist.github.com/nunsie/5e367a13209bdf767191eeb3f4730068

replace: `https://download.bytesized-hosting.com/install-bcd`
with: `https://gist.githubusercontent.com/nunsie/5e367a13209bdf767191eeb3f4730068/raw/653def668d649f5185d655417c47b0954c3801d0/install-bcd`

**Comment by maran** [comment]
Sorry about that! SSL should be back in action :)
