### ISSUE TITLE
Find some way to bring Filebot in the mix

### ISSUE THREAD

**Issue by maran** [bytesizedhosting/bcd#7]
Right now we are depending on renaming from Sickrage/Sonarr and friends for content to be properly sorted. I would love to find a good way to bring Filebot into the mix.

Of course the most powerful solution is just to install Filebot system-wide, this way you can have all the freedom of the total filesystem.

However it would be fitting to also offer a dockerized way of running filebot. However since the paths inside of Docker are quite different from those on the outside this might be a problem. We also don't want to have to manually run Filebot every time but make it a service.

The first step would be to do some research to see how Filebot can be used inside a container while still having valid symlinks being created as I feel sym- and hardlinks are the best way to use Filebot. 

The second step could be a separate binary that watches a given path for changes and then runs Filebot automatically on the changed files. 

The third important thing is that it should follow the Connect laid our paths media/tv and media/movies.

**Comment by maran** [comment]
As expected I can confirm the symlinks Filebot creates from within a container are completely wrong. 

That leaves the copy and move feature and to be honest I'm not even sure I would run Filebot if move and copy are the only options available.

This means that we are probably looking at Filebot outside of Connect, but I'm open to hear more opinions on the matter.

**Comment by mhriemers** [comment]
Doesn't the behaviour of symlinks inside a Docker container depend on which filesystem is used by the Docker daemon? 

See this for more information: https://forums.docker.com/t/symlinks-on-shared-volumes-not-supported/9288/40

**Comment by maran** [comment]
I don't think so.

Filebot uses relative symlinking by default. So if the input is `/input/test/data/test.file` and the ouput folder `/output` it will create a symlink that looks like `../../../output/test.file` however the outside filesystem will almost never mirror these folders as they are mounted completely differently inside of Docker.

Even without relative symlinking it would never match unless I force a very strict filesystem hierarchy on both the container and host in such a way that they both look the same filesystem wise.

I think having Filebot outside of Docker still makes the most sense with the information I have now.

**Comment by maran** [comment]
Actually what we could potentially try, albeit a bit dirty, is mount the whole BCD homefolder inside of the Filebot Docker container and then define the input and output folders based on that data. In theory the relative symlinks that would be created that way should then work. I will experiment with this.

**Comment by maran** [comment]
Released in 0.14
